In [1]:
import pandas as pd
import datetime as dt
import numpy as np
import datetime as dt
import scipy.stats as stats
from io import BytesIO
import requests
pd.options.display.max_columns = None
from tkinter import *
from tkinter.filedialog import askopenfilename
import re

In [2]:
file = askopenfilename()
report = pd.read_excel(file)
# report = pd.read_excel("/Users/drdim/Downloads/DFP_29.09.2020.xlsx")
report.head(100)

,Place Name,Date,Запросы,Показы,Клики,Деньги (с НДС),CPM
0,RTK 468x60 footer desktop,2021-11-01,7030,1033,0,2.87913,2.787153
1,RTK 468x60 footer desktop,2021-11-02,6467,1206,0,3.67883,3.050439
2,RTK 468x60 footer desktop,2021-11-03,5244,981,0,3.09632,3.156289
3,RTK 468x60 footer desktop,2021-11-04,4231,769,0,2.20583,2.868439
4,RTK 468x60 footer desktop,2021-11-05,4193,729,0,1.86563,2.559163
...,...,...,...,...,...,...,...
87,RTK Native 300x250,2021-11-11,114365,29504,4,118.84520,4.028104
88,RTK Native 300x250,2021-11-12,67944,23131,1,113.44612,4.904505
89,RTK Native 300x250,2021-11-13,30479,9019,2,37.23370,4.128362
90,RTK Native 300x250,2021-11-14,28913,8818,1,38.01828,4.311440
91,RTK Native 300x250,2021-11-15,27245,8321,2,35.95858,4.321425

In [3]:
def size_list(data):
#     print(list)
    list = re.findall(r'\d{1,4}[СCхx.С…]+\d{1,4}', data['Place Name'])
    str1 = ''.join(list)
    return str1

In [4]:
# report['Дата'] = "2021-05-05"

In [5]:
report['size'] = report.apply(size_list, axis=1)
# print(report['size'])

In [6]:
report['size'] = report['size'].replace('','Full Screen')
report['size'] = report['size'].str.replace('х','x')
report['size'] = report['size'].str.replace('x','x')
report['size'] = report['size'].str.replace('С…','x')
report['size'] = report['size'].str.replace('Сх','x')
report['size'] = report['size'].str.replace('Сx','x')

In [7]:
report['group'] = 243

In [8]:
report.columns = ['Place Name', 'Дата', 'Запросы', 'Показы', 'Клики', 'Деньги',
                    'CPM', 'size', 'group']

In [9]:
report = report[['Дата',
                 'group',
                 'Показы',
                 'Клики',
                 'CPM',
                 'size',
                 'Деньги']]
report['adb_segment']=0
report['adb_coverage']=0

In [10]:
report.columns = ['adb_extadv_date', 'adb_extadv_copmany', 'adb_extadv_view', 'adb_extadv_click', 'adb_extadv_cpm',
                 'adb_extadv_banner', 'adb_extadv_revenue', 'adb_segment', 'adb_coverage']

In [11]:
report['adb_extadv_date'] = report['adb_extadv_date'].dt.date

In [12]:
report.to_csv('G:/Py3.7/Dev_output/Отчёт Sape BI_{} {}.csv'.format(min(report['adb_extadv_date']),max(report['adb_extadv_date'])), index=False, sep=";")
report

,adb_extadv_date,adb_extadv_copmany,adb_extadv_view,adb_extadv_click,adb_extadv_cpm,adb_extadv_banner,adb_extadv_revenue,adb_segment,adb_coverage
0,2021-11-01,243,1033,0,2.787153,468x60,2.87913,0,0
1,2021-11-02,243,1206,0,3.050439,468x60,3.67883,0,0
2,2021-11-03,243,981,0,3.156289,468x60,3.09632,0,0
3,2021-11-04,243,769,0,2.868439,468x60,2.20583,0,0
4,2021-11-05,243,729,0,2.559163,468x60,1.86563,0,0
...,...,...,...,...,...,...,...,...,...
87,2021-11-11,243,29504,4,4.028104,300x250,118.84520,0,0
88,2021-11-12,243,23131,1,4.904505,300x250,113.44612,0,0
89,2021-11-13,243,9019,2,4.128362,300x250,37.23370,0,0
90,2021-11-14,243,8818,1,4.311440,300x250,38.01828,0,0
91,2021-11-15,243,8321,2,4.321425,300x250,35.95858,0,0

In [13]:
report

,adb_extadv_date,adb_extadv_copmany,adb_extadv_view,adb_extadv_click,adb_extadv_cpm,adb_extadv_banner,adb_extadv_revenue,adb_segment,adb_coverage
0,2021-11-01,243,1033,0,2.787153,468x60,2.87913,0,0
1,2021-11-02,243,1206,0,3.050439,468x60,3.67883,0,0
2,2021-11-03,243,981,0,3.156289,468x60,3.09632,0,0
3,2021-11-04,243,769,0,2.868439,468x60,2.20583,0,0
4,2021-11-05,243,729,0,2.559163,468x60,1.86563,0,0
...,...,...,...,...,...,...,...,...,...
87,2021-11-11,243,29504,4,4.028104,300x250,118.84520,0,0
88,2021-11-12,243,23131,1,4.904505,300x250,113.44612,0,0
89,2021-11-13,243,9019,2,4.128362,300x250,37.23370,0,0
90,2021-11-14,243,8818,1,4.311440,300x250,38.01828,0,0
91,2021-11-15,243,8321,2,4.321425,300x250,35.95858,0,0